apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-service
  labels:
    app: code-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-service
  template:
    metadata:
      labels:
        app: code-service
    spec:
      containers:
        - name: code-service
          image: subashreedinesh/code-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: code-service
  labels:
    job: code-service
    app: code-service
spec:
  selector:
    app: code-service
  ports:
  - name: code-service
    protocol: TCP
    port: 3500
    targetPort: 3500
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: code-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: code-service
  endpoints:
    - port: code-service 
      interval: 30s
      path: /metrics
