apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-service
  labels:
    app: code-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-service
  template:
    metadata:
      labels:
        app: code-service
    spec:
      containers:
      - name: code-service
        image: code-service:latest
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: code-service
spec:
  selector:
    app: code-service
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000
  type: ClusterIP
