apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  labels:
    app: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: varzzz/room-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3400
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: room-service
  labels:
    job: room-service
    app: room-service
spec:
  selector:
    app: room-service
  ports:
  - name: room-service
    protocol: TCP
    port: 3400
    targetPort: 3400
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: room-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: room-service
  endpoints:
    - port: room-service
      interval: 30s
      path: /metrics 
