apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service
  labels:
    app: socket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-service
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      containers:
        - name: socket-service
          image: subashreedinesh/socket-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3200
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  selector:
    app: socket-service
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
  type: LoadBalancer
