apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service
  labels:
    app: socket-service
spec:
  replicas: 1  # Adjust this based on how many replicas you want
  selector:
    matchLabels:
      app: socket-service
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      containers:
      - name: socket-service
        image: subashreedinesh/socket-service:latest  # Replace with your image if different
        ports:
        - containerPort: 3001  # Adjust based on the actual port your socket service listens on
        env:
        - name: NODE_ENV
          value: "production"  # Adjust if you're using a different environment variable
        # Add any environment variables required for your app here
        resources:
          limits:
            memory: "512Mi"  # Adjust memory limit as required
            cpu: "500m"      # Adjust CPU limit as required
          requests:
            memory: "256Mi"  # Adjust memory request as required
            cpu: "250m"      # Adjust CPU request as required

---
apiVersion: v1
kind: Service
metadata:
  name: socket-service
spec:
  selector:
    app: socket-service
  ports:
    - protocol: TCP
      port: 80  # This is the service port exposed to other services in the cluster
      targetPort: 3001  # The port on which the container is actually listening
  type: ClusterIP  # You can change this to LoadBalancer or NodePort based on your setup
