apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: varzzz/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3300
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    job: user-service
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - name: user-service-port
    protocol: TCP
    port: 3300
    targetPort: 3300
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: user-service-port 
      interval: 30s
      path: /metrics
