# #For API Gateway
# Service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-gateway
#   labels:
#     job: api-gateway
#     app: api-gateway
# spec:
#   selector:
#     app: api-gateway
#   ports:
#   - name: api-gateway
#     protocol: TCP
#     port: 3100
#     targetPort: 3100
#   type: ClusterIP

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  labels:
    release: prometheus
    app: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: api-gateway
      interval: 30s 
      path: /metrics
