version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  
  app:
    build:
      context: .
    container_name: app-container
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    command: npm start
