apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        ports:
        - containerPort: 9121
        env:
        - name: REDIS_ADDR
          value: redis://redis:6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
  - name: redis-exporter
    protocol: TCP
    port: 9121
    targetPort: 9121
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
  - port: redis-exporter
    interval: 30s 
    path: /metrics